name: 聚水潭订单换货补发
type: workflow
workflow: jst_order_exchange_resend
description: 聚水潭订单换货补发
aliases:
  - jst_order_exchange_resend
  - 聚水潭订单换货补发
  - 聚水潭补发
  - 聚水潭换货
  - 订单补发
  - 订单换货
fuzzy_keywords:
  - [聚水潭, 换货]
  - [聚水潭, 补发]
  - [订单, 换货]
  - [订单, 补发]
required_modules: []
entrypoint: jst_order_exchange_resend.py
